### ISSUE TITLE
Feature Request: Random Music Player / MugenMusic

### ISSUE THREAD

**Issue by rg-delacruz** [HolodexNet/Holodex#303]
Since I'm loving the music part of holodex, I kinda want to have a random section. Kinda like mugenclips but just random songs (including karaoke). It can also just be personal/client side unlike mugenclips.
This feature would help people find new songs they've never thought of enjoying.
Also great for work music

**Comment by sphinxrave** [comment]
Hello there @rg-delacruz !

Thanks for the feature suggestion. We are actually working on a music overhaul very soon that'll address those desires.

Can you (or other people reviewing this issue) help us answer some questions regarding this feature?

1. Should a radio feature be synchronized for a group of audiences like the _MugenClips_ feature? If so, what audience groups should be selected? 
   -  Does it have chat? What's some cheap/braindead way of getting chat going for this system in a scalable way? MugenClips doesn't scale at all since it uses a youtube chatbox LOL. (this is a technical question, ignore if you like)
2. Should a radio feature mimic Spotify-like artist radio where it plays you a random assortment of songs 'similar' or 'from' said singer? If so, to what degree of discovery should it provide at launch? 
3. If we had only time to implement one of 1 or 2, which is better?
4. Is it doing a vtuber a disservice if we 'discover' users into other vtubers? Other colleague vtubers from the same org? Other vtubers from other orgs / independents?

**Comment by rg-delacruz** [comment]
Thanks for the reply haha.
I'd be giving my personal answers for this. I hope others would put in their opinions as well.

1. I think it'd be nice to have a synchronized group as it would give like a radio station experience lol. For audience groups I could only think of by company or subgroup. Example Hololive/Holostars/HoloPro etc.
Having chat is nice to have but I'm sure implementation would be hard especially if you want it to be scalable. The only way I can think of to make it scalable is by making your own chatbox system. So no braindead way lol .You can just drop chat entirely and keep it as a future future release no rush.
2. Yea just like spotify radio. By song genre I guess?
3. 1 for me. I just want a random infinite song radio even if everything isn't similar to each other lol.
4. I think this question is subjective and everyone has different answers to this but for a random radio player, I don't think it does a disservice. I think discovering others is the purpose anyway. Even AZKi herself hosted a 48 hour event showcasing music from many different vtubers. This has helped small vtubers a lot. Also vtubers from the same org usually even recommend their own colleagues music. So I don't think there is really any harm done.

**Comment by sphinxrave** [comment]
The downsides of a radio station approach is less personalization (might be easier to develop tho), and inability to skip songs you don't wanna hear.

Ideally it'll be best if we can get source code for animenfo / r-a-dio somehow...

**Comment by TsungLinYeh** [comment]
Drop-in for Q3, I prefer 1 more. I don't think this feature needs to be personalized, and a random radio player sounds good to me.
I would love to discover songs I haven't heard before. Also, I don't think chat is critical. We don't have too much to discuss when listening except waving light sticks, lol

**Comment by uetchy** [comment]
I'd be happy if there is something like auto-generated radio stations as seen on Apple Music. I don't care whether a playlist is uniformly random shuffled or semi-automatically curated along with specific topics or artists. As for the latter, the stations could be named "Suisei Station" or "Chill Mix". For "<artist name> Station", it is a playlist of the artist's songs and other tunes that are in a similar style to them). If you keep track of your users' playback history, that could be accomplished by leveraging collaborative filtering.
