### ISSUE TITLE
Search music by artist.

### ISSUE THREAD

**Issue by SolomonWarlock** [HolodexNet/Holodex#312]
Not much to this one, I'd like to ask if it would be possible to add a feature to search for songs  by artist name, instead of only by song title. 

Or if it's already a thing, and I've just somehow not realized it.

**Comment by sphinxrave** [comment]
you can go to the artist's channel and hit the music tab.

![image](https://user-images.githubusercontent.com/62570796/125394050-e3e79200-e35d-11eb-94c3-aa781144cd14.png)

But yeah sure i guess future search systems should have artist search functionality? it's a bit awk though since we're not google and don't specialize in superduper awesome search algorithms.

**Comment by SolomonWarlock** [comment]
Ahh ofc fair enough.
