### ISSUE TITLE
Missing Clipper: SodaFunk

### ISSUE THREAD

**Issue by RingOfRage** [HolodexNet/Holodex#323]
https://www.youtube.com/channel/UC1B3Dhu4PWXz7g39xkBxswA

Any reason this clipper is not in the list of subbers/clippers?

**Comment by michaelnguyenm** [comment]
You can submit a request for clippers here (ignore the bit about being the owner of the channel or whatever, just fill in the info):
https://docs.google.com/forms/d/e/1FAIpQLSennSFS8lLbk9oP4MnkWh-cDQRMhiyHyXEkbRNg_4DMq1CZpw/viewform

However, for Sodafunk specifically, it's likely that they have not been put in because Holodex doesn't typically index clips from clippers where their content is on average, a minute long, and often, these clips are usually 1-3 lines long. In fact, there has been history of removing such clippers because it spams the feed. 

Requests are still taken via the form and the maintainers will discuss the merits of adding them though.

**Comment by sphinxrave** [comment]
What Michael said, it spams the feed. HoloEN ushered in a wave of english clippers who think clipping is just taking a good moment and making a twitch snapshot that's 30s and post it on YT with some borrowed (sometimes without permission) artwork. Making memey clips is all fine and well, but we're making a value assertion that such content shouldn't be put into the same bucket as sub/TL (just like the subreddit). So the more memes there are the less likely we are to accept a channel.

**Comment by sphinxrave** [comment]
Maybe in the future when we have better filtering tech we can build that kind of stuff in, or add a third category called Cuts that are pure clips / memes without language requirement.

**Comment by RingOfRage** [comment]
Fair point! However, I think the line is blurring between clips made for the sake of entertainment and clips made for the sake of information (i.e. Sushi clips). Before the HoloEN era, those clips primarily because the original sources are of a foreign language after all. 

If you look at Sushi and Sashimi's recent clips they are getting shorter, hovering around an average of 1.5 minutes.

So then, the question is not the definition of a 'clipper', but rather the conclusive definition of a 'clip'.
