### ISSUE TITLE
Feature request: showing MChad TL on TLdex

### ISSUE THREAD

**Issue by jsoon001** [HolodexNet/Holodex#351]
I noticed that it's now showing the LiveTL API on TLdex, but it would be also great if MChad TL would show up too. Are you planning to update on showing MChad TL on TLdex?

**Comment by GrumpyBear57** [comment]
As far as I'm aware (as the LiveTL API developer), Holodex has not added our API to their service. Perhaps you have the LiveTL extension installed, and are mistaking its embed in Holodex feature, for something Holodex has added? With our extension disabled, I don't see any reference to LiveTL, even after applying the latest Holodex update, so I'm not sure where you're seeing it. 

If you aren't referring to the LiveTL API I'm writing (very possible since we haven't even really officially launched it yet), or I'm missing/misunderstanding something else, then I apologize for butting in.

**Comment by KentoNishi** [comment]
@jsoon001 I'm a dev of the LiveTL extension, and we're currently working to bring the entire LiveTL interface as a built-in feature in Holodex. That way, it'll be able to show everything from the MChad API, LiveTL API, etc. without the Holodex guys putting in much work. 

In its current state, neither the LiveTL API nor the MChad API is included in TLdex.

**Comment by MonMonMnemonics** [comment]
@jsoon001 MChad dev here. MChad already has a working API for a long time and I did offer it to the dev way back on April, so yep, my guess is that they're dead busy. If LiveTL can bring their extension to holodex, that will also solve this issue without any need for TLdex to source from MChad.

**Comment by KentoNishi** [comment]
Damn the devs of like every vtuber app out here together on this one issue lmao

**Comment by KentoNishi** [comment]
I'm working on the livetl integration for futureproofing. I'm sure adding the mchad api to tldex won't be too hard, but when the livetl api drops + as we keep adding features, it's gonna be real tough to match all the stuff the extension has. So why not just integrate the two to save everyone time 🙃

**Comment by RiceCakess** [comment]
Just a recap, TLdex maintains a completely separate API from any of the other APIs mentioned. LiveTL guys are working on possibly bringing over the other two APIs

@MonMonMnemonics Wait, MChad was brought up in April? :astelzoom: I must have missed the message...

**Comment by KentoNishi** [comment]
> Wait, MChad was brought up in April? :astelzoom: I must have missed the message...

lolmao either way it's great that we're all moving away from ytc cuz god dammit i hate ytc so much

**Comment by MonMonMnemonics** [comment]
@RiceCakess Yup, early April to be more precise, was hoping we could share user accounts for MChad rating, comment, and request system so that anyone with the account in holodex can use those features in MChad. Although I ended up making my own account system, we can still work this part out if you're interested. And don't worry about the super late reply, figured out you guys were busy since it was only a few weeks after your public opening and then I had thesis too afterward.

**Comment by RiceCakess** [comment]
Implemented. More info in #451
