### ISSUE TITLE
Feature Request: Multiview - Channel icon behavior in top bar

### ISSUE THREAD

**Issue by EpharGy** [HolodexNet/Holodex#400]
Current behaviour has the Channel icon be removed from the top bar when it is currently in a view.
It would be handy to have the Channel Icon's remain and to work as an add (current) or remove channel (new feature)
This would assist with browsing through channels when searching for a stream to add in (ie currentl have to, clicking to add in, then having to pause the vid then click the vids trash icon to remove, sometimes streams that have just ended wont show the icons when paused, so you cant remove them, until the stream times out or browser is refreshed or all vids cleared and readded)

**Comment by RiceCakess** [comment]
You can delete them in the Media Controls without having to pause
![image](https://user-images.githubusercontent.com/3145205/132583420-43e75ab8-135c-454d-93a0-608cae802097.png)

I don't want channel icons to remain, because I don't want to overcrowd the top bar and rather hide it in a menu like Media Controls. I am open to other opinions.
