### ISSUE TITLE
[Feature] Handling when the stream doesn't allow embedding

### ISSUE THREAD

**Issue by Nandaka** [HolodexNet/Holodex#477]
I notice some of the new JP Gen6/HoloX disables the embedding function.
![image](https://user-images.githubusercontent.com/836867/144052474-528f8462-3585-4f85-8d70-7dd778eb0dde.png)

Is it possible to change iframe link to the youtube page `https://www.youtube.com/watch/Gu_0PP00TgE`, instead of the embed link `https://www.youtube.com/embed/Gu_0PP00TgE?playsinline=1&enablejsapi=1&origin=https%3A%2F%2Fholodex.net&widgetid=1`

result below using Inspect Element
![image](https://user-images.githubusercontent.com/836867/144053050-fecdca4c-d9c6-476a-be73-cb474ef0a03f.png)

I'm not sure if there is any better alternative.

**Comment by RiceCakess** [comment]
It's only possible with extension to embed www.youtube.com. Since the problem is probably temporary, we decided to just wait for embed to [enabled by Youtube after partnership](https://twitter.com/holodex/status/1464276166664069120). There's a few HoloX members that is working now, but we won't make an announcement until everyone has embed available.
