### ISSUE TITLE
Feature request: volume amplifier

### ISSUE THREAD

**Issue by Jhud69** [HolodexNet/Holodex#502]
Hello, ever since I got into vtubers I've been using holodex on occassion and I love it!
However the one thing that keeps me from using it over youtube sometimes is that on youtube I use a Firefox add-on called "Enhancer for YouTube" and one of its options that I use a lot is the volume amplifier. Sometimes youtube videos are freakishly quiet for me even on full volume for some reason and that feature is a godsend, however it unfortunately doesn't carry into holodex.
Would it be possible to implement something similar?

**Comment by sphinxrave** [comment]
This is impossible to achieve in a website since we don't own the Youtube iFrame - it's impossible to modify the audio context of a iframe you do not own.

We will keep it in mind as a possible feature for the Holodex Plus browser extension, but there are plenty of other browser extensions that do volume amplification.
