### ISSUE TITLE
[Multiview] keep video playing when changing layout

### ISSUE THREAD

**Issue by eight04** [HolodexNet/Holodex#504]
STR:

1. Visit https://holodex.net/multiview
2. Add two streams.
3. Play the second stream.
4. Delete the first stream by clicking the trash button.
5. The video iframe is destroyed and recreated.

Ideally it should reuse the iframe.

It works fine when deleting the second stream. Probably it doesn't set vue key correctly somewhere.

**Comment by sphinxrave** [comment]
Unfortunately impossible b/c Vue for some reason instead of moving the iframe redraws it. We spent a couple days looking at it a while back and it seems the easiest way to fix is to write the whole platform in React or Vue3. It seems to be a Vue2 problem.

Relevant issues:
https://github.com/vuejs/vue/issues/10331
https://github.com/vuejs/vue/issues/9473
