### ISSUE TITLE
FEATURE REQUEST: Option to split live/upcoming streams

### ISSUE THREAD

**Issue by Quackdoc** [HolodexNet/Holodex#506]
Thanks for the amazing app, it's helped me find a lot of new vtubers to watch, However on my aging laptop, and even my phone, listing all vtubers cripples the performance, to the point where it can take more than 30sec to load the page. and while I do love the upcoming streams too, the majority of time, My self personally, am just looking to see who is live. 

it would be a really nice feature to have and increase performance quite a bit on mobile and aging hardware.

**Comment by sphinxrave** [comment]
Sorry, if you have a good UI suggestion please make it, but otherwise we won't fix it since we're happy about how the UI looks currently (and most people aren't using aging hardware analytically), and we're too busy currently to revisit.

We are open to someone else contributing the PR for this feature, as it involves modifying the settings storage, the settings page to add a toggle, and adding a optional rendering to the Home Fave pages.👍

**Comment by RiceCakess** [comment]
Holodex 2.26 (#533) Introduces a dense list mode that should be lighter on older devices hopefully
