### ISSUE TITLE
Some vod when added to multiview cannot be synced

### ISSUE THREAD

**Issue by eviloutfromhell** [HolodexNet/Holodex#709]
When the sync toolbar is opened the bar for the vod in question disappears.
This multiview link is an example case where fauna's vod bar disappeared:
`https://holodex.net/multiview/AAKMAPhcMPzDGMs%2CAMKMJC_stWFkVdE%2CKAKMWifF8ncArM4%2CKMKMLdlNvnvnufc%2CUAEMchat0%2CUMEMchat1?t=1685239538&offsets=-5000%2C0%2C0%2C0`

**Comment by sphinxrave** [comment]
This is odd in that the Fauna video doesn't really feel like playing... 
`https://holodex.net/multiview/AAKMAPhcMPzDGMs%2CAMKMJC_stWFkVdE%2CKAKMWifF8ncArM4%2CKMKMLdlNvnvnufc%2CUAEMchat0%2CUMEMchat1`

I'm not sure how it works, but perhaps the v3 rewrite will resolve this issue.

**Comment by CwasonFauna** [comment]
So I was taking a look at this, looks like there's an issue with the very large offset. possibly hitting a DB query limit or safety precaution. Here's my findings:

  Video lengths are: -> Cali, Fauna, Kronii, Gura
  Freeze priority is -> Fauna->Cali-> Gura
  _Priority does not seem to correlate with length_ 

- Fauna start_actual: 02:00:15
- Cali start_actual: "02:00:21
- Gura start_actual: 02:01:03
- Kronii start_actual: 02:03:09

No playback issue with no offset and just the time stamp ?t=1685239538

Looks like it might have to do with either how the query is constructed or how start_actual is being used
I'll look more into this tomorrow (hopefully) though I'm not sure if I have access to the backend code for the DB since I'm fresh-fresh. 


Freeze Fauna (Original issue):
`https://holodex.net/multiview/AAKMAPhcMPzDGMs%2CAMKMJC_stWFkVdE%2CKAKMWifF8ncArM4%2CKMKMLdlNvnvnufc%2CUAEMchat0%2CUMEMchat1?t=1685239538&offsets=-5000,0,0,0`

Freeze Cali:
`https://holodex.net/multiview/AAMYAPhcMPzDGMs%2CMAMMJC_stWFkVdE%2CMMMMWifF8ncArM4?t=1685239538&offsets=-5000,0,0,0`

Freeze Kronii: ??? 

Freeze Gura:
`https://holodex.net/multiview/AAMYAPhcMPzDGMs%2CMAMYJC_stWFkVdE?t=1685239538&offsets=-5000,0,0,0`

**Comment by eviloutfromhell** [comment]
As of now it seems this issue is no longer a problem. My original link has fauna's vod bar exists as normal.
If anyone can confirm so I think this issue can be closed.

**Comment by CwasonFauna** [comment]
If you're referring to [this](https://holodex.net/multiview/AAKMAPhcMPzDGMs%2CAMKMJC_stWFkVdE%2CKAKMWifF8ncArM4%2CKMKMLdlNvnvnufc%2CUAEMchat0%2CUMEMchat1?t=1685239538&offsets=-5000,0,0,0) I'm still seeing your fauna's video stopping and not syncing. Though I do not see anything disappearing so maybe its still an issue, just a different one than originally reported.

**Comment by eviloutfromhell** [comment]
By removing the offset the multiview works properly. IIRC the -5000 offset was automatically given by holodex when the problem initially occured (and gotten in the shared link). With the offset if you seek forward 1.5 hours her video works properly (just widely offset ofcourse).
